class Box{
	 public static void main(String Args[]){
		 String box1="Black";
		 String box2="White";
		 String box3="Red";
		 String box4="Pink";
		 String box5="Blue";
		 String box6="Green";
		 String box7="Gray";
		 String box8="Cyan";
		 String box9="Teal";
		 String box10="Gold";
		 String box11="Aqua";
		 String box12="Lime";
		 String box13="Rose";
		 String box14="Navy";
		 String box15="Amber";
		 String box16="Peach";
		 String box17="Plum";
		 String box18="Mint";
		 String box19="Olive";
		 String box20="Coral";
		 String box21="Ivory";
		 String box22="Beige";
		 String box23="Azure";
		 String box24="Lilac";
		 String box25="Brown";
		 String box26="Maroon";
		 String box27="Silver";
		 String box28="Khaki";
		 String box29="Cream";
		 String box30="Violet";
		 
		 String[] Boxes={box1,box2,box3,box4,box5,box6,box7,box8,box9,box10,box11,box12,box13,box14,box15,box16,box17,box18,box19,box20,box21,box22,box23,box24,box25,box26,box27,box28,box29,box30};
		 System.out.println("First box is : "+Boxes[0]+" color");
		 System.out.println("Second box is : "+Boxes[1]+" color");
		 System.out.println("Third box is : "+Boxes[2]+" color");
		 System.out.println("Forth box is : "+Boxes[3]+" color");
		 System.out.println("Fifth box is : "+Boxes[4]+" color");
		 System.out.println("Sixth box is : "+Boxes[5]+" color");
		 System.out.println("Seventh box is : "+Boxes[6]+" color");
		 System.out.println("Eighth box is : "+Boxes[7]+" color");
		 System.out.println("Ninth box is : "+Boxes[8]+" color");
		 System.out.println("Tenth box is : "+Boxes[9]+" color");
		 System.out.println("Eleventh box is : "+Boxes[10]+" color");
		 System.out.println("Twelth box is : "+Boxes[11]+" color");
		 System.out.println("13th box is : "+Boxes[12]+" color");
		 System.out.println("14th box is : "+Boxes[13]+" color");
		 System.out.println("15th box is : "+Boxes[14]+" color");
		 System.out.println("16th box is : "+Boxes[15]+" color");
		 System.out.println("17th box is : "+Boxes[16]+" color");
		 System.out.println("18th box is : "+Boxes[17]+" color");
		 System.out.println("19th box is : "+Boxes[18]+" color");
		 System.out.println("20th box is : "+Boxes[19]+" color");
		 System.out.println("21st box is : "+Boxes[20]+" color");
		 System.out.println("22nd box is : "+Boxes[21]+" color");
		 System.out.println("23rd box is : "+Boxes[22]+" color");
		 System.out.println("24th box is : "+Boxes[23]+" color");
		 System.out.println("25th box is : "+Boxes[24]+" color");
		 System.out.println("26th box is : "+Boxes[25]+" color");
		 System.out.println("27th box is : "+Boxes[26]+" color");
         System.out.println("28th box is : "+Boxes[27]+" color");
		 System.out.println("29th box is : "+Boxes[28]+" color");
		 System.out.println("30th box is : "+Boxes[29]+" color");
		 
		 Boxes[0]="Indigo";
		 Boxes[1]="Orchid";
		 Boxes[2]="Bronze";
		 Boxes[13]="Megenta";
		 Boxes[16]="Turquoise";
		 Boxes[17]="Lavender";
		 Boxes[18]="Ruby";
		 Boxes[21]="Sienna";
		 Boxes[24]="Scarlet";
		 Boxes[29]="Jade";
		 System.out.println("First box is : "+Boxes[0]+" color");
		 System.out.println("Second box is : "+Boxes[1]+" color");
		 System.out.println("Third box is : "+Boxes[2]+" color");
		 System.out.println("Forth box is : "+Boxes[3]+" color");
		 System.out.println("Fifth box is : "+Boxes[4]+" color");
		 System.out.println("Sixth box is : "+Boxes[5]+" color");
		 System.out.println("Seventh box is : "+Boxes[6]+" color");
		 System.out.println("Eighth box is : "+Boxes[7]+" color");
		 System.out.println("Ninth box is : "+Boxes[8]+" color");
		 System.out.println("Tenth box is : "+Boxes[9]+" color");
		 System.out.println("Eleventh box is : "+Boxes[10]+" color");
		 System.out.println("Twelth box is : "+Boxes[11]+" color");
		 System.out.println("13th box is : "+Boxes[12]+" color");
		 System.out.println("14th box is : "+Boxes[13]+" color");
		 System.out.println("15th box is : "+Boxes[14]+" color");
		 System.out.println("16th box is : "+Boxes[15]+" color");
		 System.out.println("17th box is : "+Boxes[16]+" color");
		 System.out.println("18th box is : "+Boxes[17]+" color");
		 System.out.println("19th box is : "+Boxes[18]+" color");
		 System.out.println("20th box is : "+Boxes[19]+" color");
		 System.out.println("21st box is : "+Boxes[20]+" color");
		 System.out.println("22nd box is : "+Boxes[21]+" color");
		 System.out.println("23rd box is : "+Boxes[22]+" color");
		 System.out.println("24th box is : "+Boxes[23]+" color");
		  }
}