class CabSearchRunner{
	public static void main(String[] args){
		String s1="Bangalore";
		String d1="Delhi";
		int sNd1=CabSearch.getCostBySourceAndDestination(s1,d1);
		System.out.println(sNd1);
		String s2="Bangalore";
		String d2="Chennai";
		int sNd2=CabSearch.getCostBySourceAndDestination(s2,d2);
		System.out.println(sNd2);
		String s3="Bangalore";
		String d3="Jharkand";
		int sNd3=CabSearch.getCostBySourceAndDestination(s3,d3);
		System.out.println(sNd3);
		String s4="Bangalore";
		String d4="Kolkata";
		int sNd4=CabSearch.getCostBySourceAndDestination(s4,d4);
		System.out.println(sNd4);
		String s5="Delhi";
		String d5="Kolkata";
		int sNd5=CabSearch.getCostBySourceAndDestination(s5,d5);
		System.out.println(sNd5);
		String s6="Chennai";
		String d6="Kolkata";
		int sNd6=CabSearch.getCostBySourceAndDestination(s6,d6);
		System.out.println(sNd6);
		String s7="Chennai";
		String d7="Delhi";
		int sNd7=CabSearch.getCostBySourceAndDestination(s7,d7);
		System.out.println(sNd7);
		String s8="Jharkand";
		String d8="Delhi";
		int sNd8=CabSearch.getCostBySourceAndDestination(s8,d8);
		System.out.println(sNd8);
		String s9="Jharkand";
		String d9="Chennai";
		int sNd9=CabSearch.getCostBySourceAndDestination(s9,d9);
		System.out.println(sNd9);
		String s10="Jharkand";
		String d10="Varanasi";
		int sNd10=CabSearch.getCostBySourceAndDestination(s10,d10);
		System.out.println(sNd10);
		String s11="Jharkand";
		String d11="Kolkata";
		int sNd11=CabSearch.getCostBySourceAndDestination(s11,d11);
		System.out.println(sNd11);
		String s12="Varanasi";
		String d12="Chennai";
		int sNd12=CabSearch.getCostBySourceAndDestination(s12,d12);
		System.out.println(sNd12);
		String s13="Varanasi";
		String d13="Goa";
		int sNd13=CabSearch.getCostBySourceAndDestination(s13,d13);
		System.out.println(sNd13);
		
		
		String src1="Bangalore";
		String dest1="Delhi";
		int distance1=CabSearch.getDistanceBySourceAndDestination(src1,dest1);
		System.out.println(distance1);
		String src2="Bangalore";
		String dest2="Kolkata";
		int distance2=CabSearch.getDistanceBySourceAndDestination(src2,dest2);
		System.out.println(distance2);
		String src3="Bangalore";
		String dest3="Chennai";
		int distance3=CabSearch.getDistanceBySourceAndDestination(src3,dest3);
		System.out.println(distance3);
		String src4="Bangalore";
		String dest4="Jharkand";
		int distance4=CabSearch.getDistanceBySourceAndDestination(src4,dest4);
		System.out.println(distance4);
		String src5="Chennai";
		String dest5="Kolkata";
		int distance5=CabSearch.getDistanceBySourceAndDestination(src5,dest5);
		System.out.println(distance5);
		String src6="Delhi";
		String dest6="Kolkata";
		int distance6=CabSearch.getDistanceBySourceAndDestination(src6,dest6);
		System.out.println(distance6);
		String src7="Chennai";
		String dest7="Delhi";
		int distance7=CabSearch.getDistanceBySourceAndDestination(src7,dest7);
		System.out.println(distance7);
		String src8="Chennai";
		String dest8="Goa";
		int distance8=CabSearch.getDistanceBySourceAndDestination(src8,dest8);
		System.out.println(distance8);
		String src9="Chennai";
		String dest9="Kashmir";
		int distance9=CabSearch.getDistanceBySourceAndDestination(src9,dest9);
		System.out.println(distance9);
		String src10="Jharkand";
		String dest10="Kolkata";
		int distance10=CabSearch.getDistanceBySourceAndDestination(src10,dest10);
		System.out.println(distance10);
		String src11="Jharkand";
		String dest11="Chennai";
		int distance11=CabSearch.getDistanceBySourceAndDestination(src11,dest11);
		System.out.println(distance11);
		String src12="Jharkand";
		String dest12="Varanasi";
		int distance12=CabSearch.getDistanceBySourceAndDestination(src12,dest12);
		System.out.println(distance12);
		String src13="Jharkand";
		String dest13="Delhi";
		int distance13=CabSearch.getDistanceBySourceAndDestination(src13,dest13);
		System.out.println(distance13);
		String src14="Varanasi";
		String dest14="Chennai";
		int distance14=CabSearch.getDistanceBySourceAndDestination(src14,dest14);
		System.out.println(distance14);
		String src15="Kashmir";
		String dest15="varanasi";
		int distance15=CabSearch.getDistanceBySourceAndDestination(src15,dest15);
		System.out.println(distance15);
		String src16="Kashmir";
		String dest16="Kolkata";
		int distance16=CabSearch.getDistanceBySourceAndDestination(src16,dest16);
		System.out.println(distance16);
		String src17="Pondicherry";
		String dest17="Chennai";
		int distance17=CabSearch.getDistanceBySourceAndDestination(src17,dest17);
		System.out.println(distance17);
		String src18="Goa";
		String dest18="Kolkata";
		int distance18=CabSearch.getDistanceBySourceAndDestination(src18,dest18);
		System.out.println(distance18);
		String src19="Goa";
		String dest19="Varanasi";
		int distance19=CabSearch.getDistanceBySourceAndDestination(src19,dest19);
		System.out.println(distance19);
		String src20="Ayodhya";
		String dest20="Chennai";
		int distance20=CabSearch.getDistanceBySourceAndDestination(src20,dest20);
		System.out.println(distance20);
		String src21="Ayodhya";
		String dest21="Delhi";
		int distance21=CabSearch.getDistanceBySourceAndDestination(src21,dest21);
		System.out.println(distance21);
		String src22="Prayagraj";
		String dest22="Chennai";
		int distance22=CabSearch.getDistanceBySourceAndDestination(src22,dest22);
		System.out.println(distance22);
		String src23="Prayagraj";
		String dest23="Goa";
		int distance23=CabSearch.getDistanceBySourceAndDestination(src23,dest23);
		System.out.println(distance23);
		
		
		CabSearch.searchAvailability("Bangalore");
		CabSearch.searchAvailability("Mangalore");
		CabSearch.searchAvailability("Pune");
		CabSearch.searchAvailability("Gadag");
		CabSearch.searchAvailability("Delhi");
		CabSearch.searchAvailability("Goa");
		CabSearch.searchAvailability("Kollam");
		CabSearch.searchAvailability("Kashmir");
		CabSearch.searchAvailability("Kerala");
		CabSearch.searchAvailability("Mumbai");
		CabSearch.searchAvailability("Durga");
		CabSearch.searchAvailability("Jammu");
		CabSearch.searchAvailability("Varanasi");
		CabSearch.searchAvailability("Dudsagar");
		CabSearch.searchAvailability("Bijapur");
		CabSearch.searchAvailability("Chittor");
		CabSearch.searchAvailability("Vizag");
		CabSearch.searchAvailability("Vijaywada");
		CabSearch.searchAvailability("Dharwad");
		CabSearch.searchAvailability("Hassan");
		CabSearch.searchAvailability("Hubli");
		CabSearch.searchAvailability("Tumkur");
		CabSearch.searchAvailability("Kolkata");
		CabSearch.searchAvailability("Pondicherry");
		
	}
}