class CountryRunner {
    public static void main(String[] args) {
        Country.CountryPopulation("Montenegro");
		Country.CountryPopulation("Morocco");
		Country.CountryPopulation("Mozambique");
		Country.CountryPopulation("Myanmar");
		Country.CountryPopulation("Namibia");
		Country.CountryPopulation("Nauru");
		Country.CountryPopulation("Nepal");
		Country.CountryPopulation("Netherlands");
		Country.CountryPopulation("New Zealand");
		Country.CountryPopulation("Nicaragua");
		Country.CountryPopulation("Niger");
		Country.CountryPopulation("North Korea");
		Country.CountryPopulation("North Macedonia");
		Country.CountryPopulation("Norway");
		Country.CountryPopulation("Oman");
		Country.CountryPopulation("Palau");
		Country.CountryPopulation("Panama");
		Country.CountryPopulation("Papua New Guinea");
		Country.CountryPopulation("Paraguay");
		Country.CountryPopulation("Peru");
		Country.CountryPopulation("Poland");
		Country.CountryPopulation("Portugal");		
		Country.CountryPopulation("Qatar");
		Country.CountryPopulation("Romania");
		Country.CountryPopulation("Rwanda");
		Country.CountryPopulation("Slovenia");
		Country.CountryPopulation("Saudi Arabia");
		Country.CountryPopulation("Senegal");
		Country.CountryPopulation("Serbia");
		Country.CountryPopulation("Seychelles");
		Country.CountryPopulation("Singapore");
		Country.CountryPopulation("Slovakia");
		Country.CountryPopulation("Somalia");		
		Country.CountryPopulation("Sudan");
		Country.CountryPopulation("Sweden");
		Country.CountryPopulation("Switzerland");
		Country.CountryPopulation("Syria");
		Country.CountryPopulation("Tajikistan");
		Country.CountryPopulation("Tanzania");
		Country.CountryPopulation("Thailand");
		Country.CountryPopulation("Tunisia");
		Country.CountryPopulation("Turkmenistan");
		Country.CountryPopulation("Uganda");
		Country.CountryPopulation("Ukraine");		
		Country.CountryPopulation("United Arab Emirates");
		Country.CountryPopulation("Uruguay");
		Country.CountryPopulation("Uzbekistan");
		Country.CountryPopulation("Vanuatu");
		Country.CountryPopulation("Vatican City");
		Country.CountryPopulation("Venezuela");
		Country.CountryPopulation("Yemen");
		Country.CountryPopulation("Zambia");
		Country.CountryPopulation("Zimbabwe");
		Country.CountryPopulation("Bahamas");
		Country.CountryPopulation("Bahrain");	
		Country.CountryPopulation("Bangladesh");
		Country.CountryPopulation("Barbados");
		Country.CountryPopulation("Belarus");
		Country.CountryPopulation("Belgium");
		Country.CountryPopulation("Belize");
		Country.CountryPopulation("Benin");
		Country.CountryPopulation("Bhutan");
		Country.CountryPopulation("Bolivia");
		Country.CountryPopulation("Bosnia and Herzegovina");
		Country.CountryPopulation("Botswana");
		Country.CountryPopulation("Brunei");
		Country.CountryPopulation("Bulgaria");
		Country.CountryPopulation("Burkina Faso");
		Country.CountryPopulation("Burundi");
		Country.CountryPopulation("Cambodia");
		Country.CountryPopulation("Cameroon");
		Country.CountryPopulation("Canada");
		Country.CountryPopulation("Cape Verde");
		Country.CountryPopulation("Central African Republic");
		Country.CountryPopulation("Chad");
		Country.CountryPopulation("Chile");
		Country.CountryPopulation("Comoros");
		Country.CountryPopulation("Congo");
		Country.CountryPopulation("Costa Rica");
		Country.CountryPopulation("Cote d'Ivoire");
		Country.CountryPopulation("Croatia");
		Country.CountryPopulation("Cuba");
		Country.CountryPopulation("Cyprus");
		Country.CountryPopulation("Czech Republic");
		Country.CountryPopulation("Denmark");
		Country.CountryPopulation("Djibouti");
		Country.CountryPopulation("Dominica");
		Country.CountryPopulation("Dominican Republic");		
		Country.CountryPopulation("Eswatini");
		Country.CountryPopulation("Ethiopia");
		Country.CountryPopulation("Fiji");
		Country.CountryPopulation("Gambia");
		Country.CountryPopulation("East Timor");
		Country.CountryPopulation("Ghana");
		Country.CountryPopulation("Grenada");
		Country.CountryPopulation("Guinea");
		Country.CountryPopulation("Guinea-Bissau");
		Country.CountryPopulation("Guyana");
		Country.CountryPopulation("Kiribati");
		Country.CountryPopulation("Malawi");
		Country.CountryPopulation("Marshall Islands");
		Country.CountryPopulation("Samoa");
		Country.CountryPopulation("Micronesia");
		Country.CountryPopulation("Sao Tome and Principe");
		Country.CountryPopulation("Solomon Islands");
		Country.CountryPopulation("South Sudan");
		Country.CountryPopulation("Suriname");
		Country.CountryPopulation("Togo");
		Country.CountryPopulation("Tonga");
		Country.CountryPopulation("Tuvalu");		
		Country.CountryPopulation("Mongolia");
		Country.CountryPopulation("Monaco");
		Country.CountryPopulation("Moldova");
		Country.CountryPopulation("Mexico");
		Country.CountryPopulation("Mauritius");
		Country.CountryPopulation("Mauritania");
		Country.CountryPopulation("Malta");
		Country.CountryPopulation("Mali");
		Country.CountryPopulation("Maldives");
		Country.CountryPopulation("Malaysia");
		Country.CountryPopulation("Malawi");		
		Country.CountryPopulation("Madagascar");
		Country.CountryPopulation("Luxembourg");
		Country.CountryPopulation("Lithuania");
		Country.CountryPopulation("Liechtenstein");
		Country.CountryPopulation("Libya");
		Country.CountryPopulation("Liberia");
		Country.CountryPopulation("Lesotho");
		Country.CountryPopulation("Lebanon");
		Country.CountryPopulation("Latvia");
		Country.CountryPopulation("Laos");
		Country.CountryPopulation("Kyrgyzstan");		
		Country.CountryPopulation("Kuwait");
		Country.CountryPopulation("Kenya");
		Country.CountryPopulation("Kazakhstan");
		Country.CountryPopulation("Jordan");
		Country.CountryPopulation("Jamaica");
		Country.CountryPopulation("Ireland");
		Country.CountryPopulation("Honduras");
		Country.CountryPopulation("Haiti");
		Country.CountryPopulation("Guatemala");
		Country.CountryPopulation("Iceland");
		Country.CountryPopulation("Hungary");		
		Country.CountryPopulation("Greece");
		Country.CountryPopulation("Georgia");
		Country.CountryPopulation("Gabon");
		Country.CountryPopulation("Finland");
		Country.CountryPopulation("Fiji");
		Country.CountryPopulation("Eswatini");
		Country.CountryPopulation("Estonia");
		Country.CountryPopulation("Eritrea");
		Country.CountryPopulation("Equatorial Guinea");
		Country.CountryPopulation("El Salvador");
		Country.CountryPopulation("Ecuador");		
		Country.CountryPopulation("Dominican Republic");
		Country.CountryPopulation("Dominica");
		Country.CountryPopulation("Djibouti");
		Country.CountryPopulation("Denmark");
		Country.CountryPopulation("Czech Republic");
		Country.CountryPopulation("Cyprus");
		Country.CountryPopulation("Cuba");
		Country.CountryPopulation("Croatia");
		Country.CountryPopulation("Costa Rica");
		Country.CountryPopulation("Comoros");
		Country.CountryPopulation("India");		
		Country.CountryPopulation("Chile");
		Country.CountryPopulation("Chad");
		Country.CountryPopulation("Central African Republic");
		Country.CountryPopulation("cape Verde");
		Country.CountryPopulation("Canada");
		Country.CountryPopulation("Cameroon");
		Country.CountryPopulation("Cambodia");
		Country.CountryPopulation("Burundi");
		Country.CountryPopulation("Burkina Faso");
		Country.CountryPopulation("Bulgaria");
		Country.CountryPopulation("Brunei");
		Country.CountryPopulation("Botswana");
		Country.CountryPopulation("Bosnia and Herzegovina");
		Country.CountryPopulation("Bolivia");
		Country.CountryPopulation("Bhutan");
		Country.CountryPopulation("Benin");
		Country.CountryPopulation("Belize");
		Country.CountryPopulation("Belgium");
		Country.CountryPopulation("Belarus");
		Country.CountryPopulation("Barbados");
		Country.CountryPopulation("Bahrain");
		Country.CountryPopulation("Azerbaijan");	
		Country.CountryPopulation("Austria");
		Country.CountryPopulation("Australia");
		Country.CountryPopulation("Armenia");
		Country.CountryPopulation("Antigua and Barbuda");
		Country.CountryPopulation("Angola");
		Country.CountryPopulation("Andorra");
		Country.CountryPopulation("Algeria");
		Country.CountryPopulation("Albania");
		Country.CountryPopulation("Afghanistan");
		Country.CountryPopulation("Argentina");
		Country.CountryPopulation("Spain");
		Country.CountryPopulation("Colombia");
		Country.CountryPopulation("South Korea");
		Country.CountryPopulation("South Africa");
		Country.CountryPopulation("Italy");
		Country.CountryPopulation("UK");
		Country.CountryPopulation("France");
		Country.CountryPopulation("Germany");
		Country.CountryPopulation("Turkey");
		Country.CountryPopulation("Vietnam");
		Country.CountryPopulation("Egypt");
		Country.CountryPopulation("Philippines");
		Country.CountryPopulation("Ethiopia");
		Country.CountryPopulation("Japan");
		Country.CountryPopulation("Mexico");
		Country.CountryPopulation("Russia");
		Country.CountryPopulation("Bangladesh");
		Country.CountryPopulation("Nigeria");
		Country.CountryPopulation("Brazil");
		Country.CountryPopulation("Pakistan");
		Country.CountryPopulation("Indonesia");
		Country.CountryPopulation("USA");
		Country.CountryPopulation("China");
		
	}
}	
		